# Generated by Django 4.2.7 on 2023-11-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_connections_kafkatopics_restapis_sparkjobs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connections',
            options={'verbose_name_plural': 'Connections'},
        ),
        migrations.AlterModelOptions(
            name='joblogs',
            options={'verbose_name_plural': 'Job Logs'},
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='kafkatopics',
            options={'verbose_name_plural': 'Kafka Topics'},
        ),
        migrations.AlterModelOptions(
            name='restapis',
            options={'verbose_name_plural': 'Rest Apis'},
        ),
        migrations.AlterModelOptions(
            name='sparkjobs',
            options={'verbose_name_plural': 'Spark Jobs'},
        ),
        migrations.AlterModelOptions(
            name='steplogs',
            options={'verbose_name_plural': 'Step Logs'},
        ),
        migrations.AlterModelOptions(
            name='steps',
            options={'verbose_name_plural': 'Steps'},
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
